export const is_logistics = (dept_code) => dept_code?.includes(2);
export const is_plant = (dept_code) => dept_code?.includes(1);
export const is_buyrent = (dept_code) => dept_code?.includes(3);
export const is_hod = (role) => role.includes("hod");
export const is_gm = (role) => role.includes("gm");
export const is_ceo = (role) => role.includes("ceo");
export const is_asset = (role) => role.includes("inita");
export const is_fm = (role) => role.includes("fm");
export const is_fnote = (role) => role.includes("initfn");
